services:
  typing-ex:
    image: clojure:latest
    # user: vscode
    environment:
      TP_DEV: true
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs
    entrypoint:
      - sleep
      - infinity
    ports:
      - 3003:3003
      - 6666:6666

  db:
    image: postgres:17
    restart: unless-stopped
    # env_file: .env
    environment:
      POSTGRES_DB: typing_ex
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Toky
    ports:
      - 5433:5432
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
      - ./db-dumps/redis:/data

volumes:
  # data:
  #   driver: local
  gitlibs:
    external: true
  m2:
    external: true
  # redis:
  #   driver: local
