version: "3.3"

services:
  db:
    image: postgres:14.7
    restart: unless-stopped
    environment:
      - POSTGRES_DB=typing_ex
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=Asia/Tokyo
    ports:
      - "55432:5432"
    volumes:
      - data:/var/lib/postgres/data

  app:
    image: hkim0331/luminus:latest
    tty: true
    # environment:
    #   - LEIN_REPL_PORT=8888
    #   - LEIN_REPL_HOST=0.0.0.0
    ports:
      - "3023:3023"
      # - "8888:8888"
    volumes:
      - .:/usr/src/app
      - m2:/root/.m2
      - gitlibs:/root/.gitlibs

volumes:
  m2:
    external: true
  gitlibs:
    external: true
  data:
    driver: local
